#define ZCC_EQ                               1
#define ZCC_MULEQ                            2
#define ZCC_DIVEQ                            3
#define ZCC_MODEQ                            4
#define ZCC_ADDEQ                            5
#define ZCC_SUBEQ                            6
#define ZCC_LSHEQ                            7
#define ZCC_RSHEQ                            8
#define ZCC_ANDEQ                            9
#define ZCC_OREQ                            10
#define ZCC_XOREQ                           11
#define ZCC_URSHEQ                          12
#define ZCC_QUESTION                        13
#define ZCC_COLON                           14
#define ZCC_OROR                            15
#define ZCC_ANDAND                          16
#define ZCC_EQEQ                            17
#define ZCC_NEQ                             18
#define ZCC_APPROXEQ                        19
#define ZCC_LT                              20
#define ZCC_GT                              21
#define ZCC_LTEQ                            22
#define ZCC_GTEQ                            23
#define ZCC_LTGTEQ                          24
#define ZCC_IS                              25
#define ZCC_DOTDOT                          26
#define ZCC_OR                              27
#define ZCC_XOR                             28
#define ZCC_AND                             29
#define ZCC_LSH                             30
#define ZCC_RSH                             31
#define ZCC_URSH                            32
#define ZCC_SUB                             33
#define ZCC_ADD                             34
#define ZCC_MUL                             35
#define ZCC_DIV                             36
#define ZCC_MOD                             37
#define ZCC_CROSSPROD                       38
#define ZCC_DOTPROD                         39
#define ZCC_POW                             40
#define ZCC_UNARY                           41
#define ZCC_ADDADD                          42
#define ZCC_SUBSUB                          43
#define ZCC_DOT                             44
#define ZCC_LPAREN                          45
#define ZCC_LBRACKET                        46
#define ZCC_SCOPE                           47
#define ZCC_EOF                             48
#define ZCC_SEMICOLON                       49
#define ZCC_COMMA                           50
#define ZCC_INCLUDE                         51
#define ZCC_EXTEND                          52
#define ZCC_CLASS                           53
#define ZCC_IDENTIFIER                      54
#define ZCC_ABSTRACT                        55
#define ZCC_NATIVE                          56
#define ZCC_UI                              57
#define ZCC_PLAY                            58
#define ZCC_REPLACES                        59
#define ZCC_VERSION                         60
#define ZCC_STRCONST                        61
#define ZCC_RPAREN                          62
#define ZCC_DEFAULT                         63
#define ZCC_COLOR                           64
#define ZCC_LBRACE                          65
#define ZCC_RBRACE                          66
#define ZCC_PROPERTY                        67
#define ZCC_STRUCT                          68
#define ZCC_CLEARSCOPE                      69
#define ZCC_CONST                           70
#define ZCC_ENUM                            71
#define ZCC_STATES                          72
#define ZCC_NWS                             73
#define ZCC_STOP                            74
#define ZCC_WAIT                            75
#define ZCC_FAIL                            76
#define ZCC_LOOP                            77
#define ZCC_GOTO                            78
#define ZCC_SUPER                           79
#define ZCC_BRIGHT                          80
#define ZCC_FAST                            81
#define ZCC_SLOW                            82
#define ZCC_NODELAY                         83
#define ZCC_CANRAISE                        84
#define ZCC_OFFSET                          85
#define ZCC_LIGHT                           86
#define ZCC_SBYTE                           87
#define ZCC_BYTE                            88
#define ZCC_SHORT                           89
#define ZCC_USHORT                          90
#define ZCC_INT                             91
#define ZCC_UINT                            92
#define ZCC_BOOL                            93
#define ZCC_FLOAT                           94
#define ZCC_DOUBLE                          95
#define ZCC_VECTOR2                         96
#define ZCC_VECTOR3                         97
#define ZCC_NAME                            98
#define ZCC_SOUND                           99
#define ZCC_STATE                          100
#define ZCC_LET                            101
#define ZCC_ATSIGN                         102
#define ZCC_READONLY                       103
#define ZCC_STRING                         104
#define ZCC_MAP                            105
#define ZCC_ARRAY                          106
#define ZCC_VOID                           107
#define ZCC_UINT8                          108
#define ZCC_INT8                           109
#define ZCC_UINT16                         110
#define ZCC_INT16                          111
#define ZCC_RBRACKET                       112
#define ZCC_ACTION                         113
#define ZCC_DEPRECATED                     114
#define ZCC_STATIC                         115
#define ZCC_PRIVATE                        116
#define ZCC_PROTECTED                      117
#define ZCC_LATENT                         118
#define ZCC_FINAL                          119
#define ZCC_META                           120
#define ZCC_TRANSIENT                      121
#define ZCC_VIRTUAL                        122
#define ZCC_OVERRIDE                       123
#define ZCC_VARARG                         124
#define ZCC_VIRTUALSCOPE                   125
#define ZCC_ELLIPSIS                       126
#define ZCC_IN                             127
#define ZCC_OUT                            128
#define ZCC_OPTIONAL                       129
#define ZCC_TILDE                          130
#define ZCC_BANG                           131
#define ZCC_SIZEOF                         132
#define ZCC_ALIGNOF                        133
#define ZCC_INTCONST                       134
#define ZCC_UINTCONST                      135
#define ZCC_FLOATCONST                     136
#define ZCC_NAMECONST                      137
#define ZCC_FALSE                          138
#define ZCC_TRUE                           139
#define ZCC_NULLPTR                        140
#define ZCC_STATICCONST                    141
#define ZCC_CONTINUE                       142
#define ZCC_BREAK                          143
#define ZCC_RETURN                         144
#define ZCC_DO                             145
#define ZCC_FOR                            146
#define ZCC_WHILE                          147
#define ZCC_UNTIL                          148
#define ZCC_IF                             149
#define ZCC_ELSE                           150
#define ZCC_SWITCH                         151
#define ZCC_CASE                           152
